import java.util.Random;

public class Task3 {
    public static void main(String [] args) {
        int d1 = 0; //will hold random int generated by Random class
        int d2 = 0; //will hold random int generated by Random class
        int d3 = 0; //will hold random int generated by Random class
        int sum = 0;
        Random rand = new Random();
        do {
            for(int i = 1; i <= 3; i++) {
                d1 = rand.nextInt(6) + 1;
                d2 = rand.nextInt(6) + 1;
                d3 = rand.nextInt(6) + 1;
                System.out.println(d1);
                System.out.println(d2);
                System.out.println(d3);
            }
        } while (d1 == d2 || d2 == d3);
        sum = d1+ d2 + d3;

        System.out.printf();
    }
}
