import java.util.Random;

public class Task3 {
    public static void main(String [] args) {
        int d1 = 0; //will hold random int generated by Random class
        int d2 = 0; //will hold random int generated by Random class
        int d3 = 0; //will hold random int generated by Random class
        int sum = 0;
        int rollCount = 0;
        Random rand = new Random();

        System.out.printf("%-5s%-5s%-5s%-5s%-5s", "Roll", "Die1", "Die2", "Die3", "Sum");
        System.out.printf("\n%-1s%1s%1s%1s%1s%1s%1s%1s%1s%1s%1s%1s%1s%1s%1s%1s%1s%1s%1s%1s%1s%1s%1s", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "");
        do {
                d1 = rand.nextInt(6) + 1;
                d2 = rand.nextInt(6) + 1;
                d3 = rand.nextInt(6) + 1;
                sum = d1+ d2 + d3;
                rollCount++;

            System.out.printf("\n%-5d%-5d%-5d%-5d%-5d", rollCount,d1, d2, d3, sum);
        } while (d1 != d2 || d2 != d3);
    }
}
